name: Create auto commits every minute
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name pinglinh
          git config user.email github-actions@github.com
          git commit --allow-empty -m "Empty commit"
          git push
