name: auto-commit
on:
  schedule:
  - cron: "*/5 * * *"

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      EMAIL: ${{ secrets.EMAIL }}
    steps:
      - uses: actions/checkout@v2
      - run: |-
          git config user.email "$USERNAME"
          git config user.name "$EMAIL"
          git commit --allow-empty -m "Updated commit"
          git push
