name: auto-commit
on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git commit --allow-empty -m "Empty commit"
          git push
