name: auto-commit
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      EMAIL: ${{ secrets.EMAIL }}
    steps:
      - uses: actions/checkout@v2
      - run: |-
          git config commit.gpgsign true
          git config user.name "$USERNAME"
          git config user.email "$EMAIL"
          git commit -S --allow-empty -m "Updated commit"
          git push
